[project]
name = "my-project"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/Users/chris/.clarinet/cache"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.MIT-Hackathon-NFT]
path = "contracts/MIT-Hackathon-NFT.clar"
depends_on = ["nft-trait"]

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
